# 넘파이 만들기

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [5]:
arr2 = np.array([[1, 2, 3], [10, 20, 30]])
arr2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
type(arr2)

numpy.ndarray

In [10]:
# np.array가 아니라 np.arange
# 1 <= arr3 <= 9 1씩 증가

arr3 = np.arange(1, 10, 1)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 0~1 사이 

arr4 = np.random.random((2, 5))
arr4

array([[0.44012855, 0.48226594, 0.70178457, 0.2307748 , 0.12141293],
       [0.72527465, 0.75625784, 0.14975101, 0.25474179, 0.88224296]])

In [25]:
# Uniform Distribution : 균일분포, 균등분포

arr6 = np.random.rand(10)
arr6

array([0.53632398, 0.08009781, 0.44401493, 0.38430808, 0.52858465,
       0.79843498, 0.51575282, 0.83692741, 0.18114876, 0.94334832])

In [20]:
# Nomal Distribustion : 정규분포

arr7 = np.random.randn(10)
arr7

array([-1.50781241, -1.82352338,  0.43518166,  1.28441541,  0.74740694,
       -0.92423444, -0.1025726 ,  0.49363615, -0.46907963,  1.12350213])

In [21]:
# 정수 값만 return하는 함수 
# 하이퍼파라미터를 의무적으로 하나 이상을 적어야 함
# low : 하나의 하이퍼파라미터를 적으면 그 값은 가장 높은 범주의 값으로 인식하고 0에서부터
#       그 숫자 사이의 int를 하나 반환
# high : optional
# size : 몇 개의 random값을 리턴하기를 바라는지
# dtype : optional

arr8 = np.random.randint(low=10, high=20, size=5)
arr8

array([17, 11, 12, 15, 19])

In [27]:
# 안에는 배열을 넣을 수 있기 때문에 arr9 가능

arr8 = np.random.choice([1, 2, 3, 4, 5], 2)
arr8

array([2, 4])

In [34]:
arr9 = np.random.choice(np.arange(1, 10, 2), 2)
np.random.shuffle(arr9) # 데이터가 셔플
arr9

array([1, 3])

In [35]:
arr10 = np.int32([2, 3, 4])
arr10

# int64
# float32
# str

array([2, 3, 4])

In [40]:
arr11 = np.str([2, 3, 4])
arr11

'[2, 3, 4]'

In [39]:
arr12 = np.array([2, 3, 4], dtype=np.int32)
arr12

array([2, 3, 4])

In [41]:
arr13 = np.ones(5)
arr13

array([1., 1., 1., 1., 1.])

In [42]:
arr14 = np.zeros(5)
arr14

array([0., 0., 0., 0., 0.])

In [44]:
arr15 = np.eye(10)
arr15

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
# 간격이 균일하게 디폴트 값인 50개를 만들어 줌

arr16 = np.linspace(1, 5)
arr16

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [48]:
arr17 = np.linspace(1, 5, 10)
arr17

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
# return_counts : 값이 True이면 중복되지 않는 요소들이 입력 배열에 나타난 횟수를 리턴
# return_index : 값이 True이면 입력 배열의 요소들의 인덱스를 리턴
# return_inverse : 값이 True이면 입력 배열을 재구성할 때 쓰이는 고유 배열의 인덱스를 반환

v, c = np.unique([1, 1, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 7], return_counts=True)

for a, b in zip(v, c):
    print(f'{a}는 {b}개')

1는 2개
3는 3개
5는 4개
7는 5개


In [60]:
v, idx = np.unique([1, 1, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 7], return_index=True)

for a, b in zip(v, idx):
    print(f'{a}는 {b} 인덱스')

1는 0 인덱스
3는 2 인덱스
5는 5 인덱스
7는 9 인덱스


# 시리즈 만들기

In [79]:
import pandas as pd

In [80]:
# 리스트, 튜플, 딕셔너리 넣을 수 있음

l = [1, 2, 3]
t = (1, 2, 3)
d = {'a':1, 'b':2, 'c':3}

In [81]:
# name : 시리즈 이름
# dtype : 타입 지정
# index :인덱스 부여 - 만약에 안 적는다면 0, 1, ..

sr1 = pd.Series(l, index=['a', 'b', 'c'], dtype=np.float64, name='kor')
sr1

a    1.0
b    2.0
c    3.0
Name: kor, dtype: float64

In [82]:
sr2 = pd.Series(t)
sr2

0    1
1    2
2    3
dtype: int64

In [83]:
sr3 = pd.Series(d)
sr3

a    1
b    2
c    3
dtype: int64

In [85]:
# 인덱스 바꾸기 

sr3.index = ['aa', 'bb', 'cc']
sr3

aa    1
bb    2
cc    3
dtype: int64

# 데이터프레임 만들기

In [71]:
# 리스트 리스트
l2 = [[1,2],[3,4],[5,6]]

# 튜플 리스트
t2 = [(1,2),(3,4),(5,6)]

# 딕셔너리 리스트
d2 = [{'kor':1, 'eng':2},
      {'kor':3, 'eng':4},
      {'kor':5, 'eng':6}]

In [75]:
# index : 인덱스 부여
# columns : 칼럼 부여

df1 = pd.DataFrame(l2, index=['a', 'b', 'c'], columns=['kor', 'eng'])
df1

kor  eng
a    1    2
b    3    4
c    5    6

In [76]:
df2 = pd.DataFrame(t2, index=['a', 'b', 'c'], columns=['kor', 'eng'])
df2

kor  eng
a    1    2
b    3    4
c    5    6

In [78]:
df3 = pd.DataFrame(d2)
df3

kor  eng
0    1    2
1    3    4
2    5    6