In [1]:
import numpy as np
import pandas as pd

# 넘파이

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
# 기본이 int32

arr1.dtype

dtype('int32')

In [20]:
arr1.astype(np.int64)
arr1.dtype

# np.int64
# np.float64
# np.str

dtype('int32')

In [21]:
# dtype은 데이터 타입을 말하는 거
# type이랑 다름

type(arr1)

numpy.ndarray

In [5]:
arr1.size

5

In [6]:
arr1.shape

(5,)

In [23]:
arr1.reshape(-1, 5)

array([[1, 2, 3, 4, 5]])

In [7]:
arr1.ndim

1

In [9]:
arr2 = np.array([[1, 2, 3], [10, 20, 30]])
arr2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [10]:
arr2.dtype

dtype('int32')

In [12]:
arr2.size

6

In [13]:
# 행, 열

arr2.shape

(2, 3)

In [11]:
arr2.ndim

2

In [16]:
arr3 = arr2.T
arr3

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [17]:
arr3.shape

(3, 2)

# 시리즈

In [26]:
data = {'aa':10,'bb':20,'cc':30,'dd':40, 'ee':50}
sr1 = pd.Series(data, name='국어점수', dtype=np.int64)
sr1

aa    10
bb    20
cc    30
dd    40
ee    50
Name: 국어점수, dtype: int64

In [28]:
sr1.dtype

dtype('int64')

In [29]:
sr1.ndim

1

In [30]:
sr1.shape

(5,)

In [31]:
sr1.size

5

In [32]:
sr1.name

'국어점수'

In [34]:
sr1.index

Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object')

In [35]:
type(sr1.index)

pandas.core.indexes.base.Index

In [36]:
# ndarray

sr1.values

array([10, 20, 30, 40, 50], dtype=int64)

# 데이터프레임

In [37]:
data =  {'eng':[10,30,50,70],
         'kor':[20,40,60,80],
         'math':[90,50,20,70]}
df1 = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
df1

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

In [39]:
df1.ndim

2

In [40]:
df1.shape

(4, 3)

In [41]:
df1.shape[0]

4

In [42]:
len(df1)

4

In [43]:
df1.size

12

In [44]:
df1.T

a   b   c   d
eng   10  30  50  70
kor   20  40  60  80
math  90  50  20  70

In [45]:
df1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [46]:
type(df1.index)

pandas.core.indexes.base.Index

In [47]:
df1.values

array([[10, 20, 90],
       [30, 40, 50],
       [50, 60, 20],
       [70, 80, 70]], dtype=int64)

In [48]:
# 주의 : 데이터프레임에서는 dtype이 아닌 dtypes

df1.dtypes

eng     int64
kor     int64
math    int64
dtype: object

In [50]:
# 속성은 아니지만 멤버함수인 df.info()

df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   eng     4 non-null      int64
 1   kor     4 non-null      int64
 2   math    4 non-null      int64
dtypes: int64(3)
memory usage: 288.0+ bytes
