In [2]:
import numpy as np
import pandas as pd

# 넘파이

In [4]:
arr1 = np.arange(1, 11, 1)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
# 이차원 데이터

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr2.shape

(3, 3)

### 인덱싱 - 1차원 데이터

1차원 데이터 인덱싱

In [5]:
arr1[0]

1

In [6]:
# 복수 개의 인덱스 선택

arr1[[0, 2, 4]]

array([1, 3, 5])

In [10]:
# 불리안 인덱싱

arr1[[True, True, False, True, False, True, False, True, False, True]]

array([ 1,  2,  4,  6,  8, 10])

### 슬라이싱 - 1차원 데이터

In [11]:
arr1[0:4:2]

array([1, 3])

In [12]:
arr1[0:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1[-4:-1:1]

array([7, 8, 9])

In [16]:
#  증가치 자리에 -1이 있으면 거꾸로

arr1[-1:-4:-1]

array([10,  9,  8])

In [18]:
# 참고 : 리스트내포

name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])
name

array(['홍길동', '김철수', '임꺽정', '김철이', '이황'], dtype='<U3')

In [19]:
# '철' 글자가 있는 데이터를 보여주시오
[n for n in name if '철' in n]

['김철수', '김철이']

### 2차원 데이터 인덱싱, 슬라이싱

In [ ]:
# [행, 열] : 2차원 데이터
# [면, 행, 열] : 3차원 데이터

In [97]:
arr2[1]

array([4, 5, 6])

In [98]:
arr2[1, 1]

5

In [99]:
# 복수 개의 행 선택

arr2[[1, 2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [100]:
arr2[:2, 1:2]

array([[2],
       [5]])

In [101]:
# 마지막 열을 제외하고 선택
# 특성 데이터 추출시 많이 활용

arr2[:,:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [103]:
# 마지막 열만 선택
# 라벨 추출 -> 인공지능에서 많이 사용

arr2[:,[-1]]

array([[3],
       [6],
       [9]])

In [105]:
# 2차원 데이터 불리언 인덱싱 - 행단위
# True에 해당하는 행만 선택

arr2[[True, True, False]]

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
# ndarray - 1차원 데이터

arr2[:, 0] 

array([1, 4, 7])

In [107]:
# ndarray - 2차원 데이터

arr2[:, [0]]

array([[1],
       [4],
       [7]])

# 시리즈

In [20]:
data = {'aa':10,'bb':20,'cc':30,'dd':40, 'ee':50}
sr1 = pd.Series(data, name='국어점수')
sr1

aa    10
bb    20
cc    30
dd    40
ee    50
Name: 국어점수, dtype: int64

In [22]:
type(sr1)

pandas.core.series.Series

### 인덱싱

In [21]:
sr1[1]

20

In [23]:
# 부여된 인덱스로 해당 데이터 가져오기

sr1['aa']

10

In [24]:
# 복수 개의 인덱스 선택

sr1[[0, 1, 2]]

aa    10
bb    20
cc    30
Name: 국어점수, dtype: int64

In [25]:
# 복수 개의 인덱스 선택

sr1[['aa', 'bb', 'cc']]

aa    10
bb    20
cc    30
Name: 국어점수, dtype: int64

In [30]:
# 불리안 인덱싱

sr1[[True, True, False, False, True]]

aa    10
bb    20
ee    50
Name: 국어점수, dtype: int64

### 슬라이싱

In [ ]:
# 슬라이싱은 대괄호 두개가 필요 없음

In [26]:
sr1[0:2]

aa    10
bb    20
Name: 국어점수, dtype: int64

In [27]:
sr1[:-1]

aa    10
bb    20
cc    30
dd    40
Name: 국어점수, dtype: int64

In [28]:
# 부여된 인덱스로 슬라이싱은 끝인덱스도 포함
    
sr1['aa':'dd']

aa    10
bb    20
cc    30
dd    40
Name: 국어점수, dtype: int64

### 인덱스가 숫자인 경우 : loc 혹은 iloc

In [ ]:
# 구분하기 쉽게 loc나 iloc로 인덱싱, 슬라이싱을 하자!

In [32]:
sr1.loc['aa']

10

In [33]:
sr1.loc['bb':'dd']

bb    20
cc    30
dd    40
Name: 국어점수, dtype: int64

In [34]:
sr1.iloc[1]

20

In [35]:
sr1.iloc[0:2]

aa    10
bb    20
Name: 국어점수, dtype: int64

### 문자열로 값이 구성된 시리즈 - str속성을 이용

sr.index.str : 문자열 index 다룰 때<br>
sr.str : 문자열 값을 다룰 때

In [75]:
sr = pd.Series(['홍길동','이순신','김철수','김순이','이홍김'] )
sr.index=['aa','bb','cc','dd','ee'] # 인덱스 지정
sr

aa    홍길동
bb    이순신
cc    김철수
dd    김순이
ee    이홍김
dtype: object

In [76]:
sr.index

Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object')

In [77]:
sr.index.str

In [78]:
sr.str

In [79]:
# 첫번째 글자만 출력

sr.str[0]

aa    홍
bb    이
cc    김
dd    김
ee    이
dtype: object

In [80]:
# 두번째 글자 이후로 출력

sr.str[1:]

aa    길동
bb    순신
cc    철수
dd    순이
ee    홍김
dtype: object

### 문자열 데이터 검색 - 정규식 이용

In [82]:
# 정규식 패턴을 이용해서 문자열을 검색 : contains
# contains 안에는 문자열이 들어가야 함

sr[sr.str.contains('김')]

cc    김철수
dd    김순이
ee    이홍김
dtype: object

In [83]:
# '김' 글자로 시작

sr[sr.str.contains('^김')]

cc    김철수
dd    김순이
dtype: object

In [84]:
# '김' 글자로 끝남

sr[sr.str.contains('김$')]

ee    이홍김
dtype: object

In [85]:
# [] : 문자의 집합 중 하나 / '홍' 또는 '이'라는 글자가 들어 있는 것은 다 가져옴

sr[sr.str.contains('[홍이]')]

aa    홍길동
bb    이순신
dd    김순이
ee    이홍김
dtype: object

In [86]:
# 홍순 또는 이순 이라는 글자가 들어 있는 것을 가져옴 -> 이순신

sr[sr.str.contains('[홍이]순')]

bb    이순신
dtype: object

In [87]:
# 길동 또는 순이 또는 이홍 이라는 글자가 들어 있는 것을 가져옴

sr[sr.str.contains('길동|순이|이홍')]

aa    홍길동
dd    김순이
ee    이홍김
dtype: object

특정 문자열로 바꾸기

In [88]:
# '김'을 '황'으로 바꾸어라

sr.str.replace('김', '황')

aa    홍길동
bb    이순신
cc    황철수
dd    황순이
ee    이홍황
dtype: object

In [89]:
# 김으로 시작하는 글자를 황으로 바꾸어라

sr.str.replace('^김', '황')

aa    홍길동
bb    이순신
cc    황철수
dd    황순이
ee    이홍김
dtype: object

In [90]:
# 김으로 끝나는 글자를 황으로 바꾸어라

sr.str.replace('김$', '황')

aa    홍길동
bb    이순신
cc    김철수
dd    김순이
ee    이홍황
dtype: object

In [92]:
# 김철 또는 김이를 황으로 바꾸어라

sr.str.replace('김[철이]', '황')

aa    홍길동
bb    이순신
cc     황수
dd    김순이
ee    이홍김
dtype: object

sr.index.str을 이용

In [93]:
sr[ sr.index.str.contains('a')]

aa    홍길동
dtype: object

# 데이터프레임

In [36]:
data =  {'eng':[10,30,50,70],
         'kor':[20,40,60,80],
         'math':[90,50,20,70]}
df1 = pd.DataFrame(data,index=['a','b','c','d'])
df1

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

### 인덱싱 -> 칼럼명과 관련

In [38]:
# df['칼럼명']

df1['eng']

a    10
b    30
c    50
d    70
Name: eng, dtype: int64

In [39]:
# 시리스

type(df1['eng'])

pandas.core.series.Series

In [41]:
# 참고 
# ndarray

type(df1['eng'].values)

numpy.ndarray

In [ ]:
# df['eng'].시리즈의 속성(메서드)

In [44]:
# 복수개 칼럼 선택 
# 데이터프레임

df1[['eng', 'kor']]

eng  kor
a   10   20
b   30   40
c   50   60
d   70   80

In [45]:
# 데이터프레임

df1[['eng']]

eng
a   10
b   30
c   50
d   70

In [46]:
# 데이터프레임

type(df1[['eng']])

pandas.core.frame.DataFrame

In [47]:
# 시리즈

type(df1['eng'])

pandas.core.series.Series

### 슬라이싱 -> row 단위

In [48]:
df1[1:2]

eng  kor  math
b   30   40    50

In [49]:
df1['a':'d']

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

### 그래도! iloc와 loc를 사용해서 인덱싱, 슬라이싱을 하자

In [ ]:
# df.iloc[행, 열]

In [51]:
df1.iloc[1, 2]

50

In [61]:
type(df1.iloc[1, 2])

numpy.int64

In [54]:
# 인덱싱, 인덱싱

df1.iloc[[0, 2, 3], [0, 1]]

eng  kor
a   10   20
c   50   60
d   70   80

In [109]:
# 시리즈로 반환

df1.iloc[[0, 2, 3], 0]

a    10
c    50
d    70
Name: eng, dtype: int64

In [111]:
type(df1.iloc[[0, 2, 3], 0])

pandas.core.series.Series

In [110]:
# 데이터프레임으로 반환

df1.iloc[[0, 2, 3], [0]]

eng
a   10
c   50
d   70

In [55]:
# 슬라이싱, 슬라이싱

df1.iloc[1:2, 2:3]

math
b    50

In [56]:
# 인덱스, 슬라이싱

df1.iloc[[2, 3], 0:2]

eng  kor
c   50   60
d   70   80

In [59]:
# 슬라이싱, 인덱싱

# 시리즈 -> 인덱스 + 값
df1.iloc[:2, 2]

a    90
b    50
Name: math, dtype: int64

In [60]:
type(df1.iloc[:2, 2])

pandas.core.series.Series

In [ ]:
# df.loc[행, 열]

In [64]:
df1.loc['a']

eng     10
kor     20
math    90
Name: a, dtype: int64

In [65]:
type(df1.loc['a'])

pandas.core.series.Series

In [67]:
df1.loc['a':'c']

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20

In [68]:
df1.loc[['a', 'b', 'c']]

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20

In [ ]:
# 인덱싱, 인덱싱

In [69]:
df1.loc['a', 'kor']

20

In [70]:
df1.loc['b', ['eng', 'math']]

eng     30
math    50
Name: b, dtype: int64

In [ ]:
# 슬라이싱, 슬라이싱

In [72]:
df1.loc['a':'c', 'eng':'kor']

eng  kor
a   10   20
b   30   40
c   50   60

In [ ]:
# 인덱싱, 슬라이싱

In [73]:
df1.loc['b', 'eng' : 'math']

eng     30
kor     40
math    50
Name: b, dtype: int64

In [ ]:
# 슬라이싱, 인덱싱

In [74]:
df1.loc['a':'c',['eng', 'kor'] ]

eng  kor
a   10   20
b   30   40
c   50   60