In [1]:
import numpy as np
import pandas as pd

# 넘파이 - 1차원 데이터

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1 + 1

array([2, 3, 4, 5, 6])

In [7]:
arr1 * 2

array([ 2,  4,  6,  8, 10])

In [8]:
arr1[(arr1 == 1) | (arr1 == 5)]

array([1, 5])

In [9]:
arr1[(arr1>2) & (arr1<5)]

array([3, 4])

In [10]:
arr1[~((arr1 == 1) | (arr1 == 5))]

array([2, 3, 4])

# 넘파이 - 2차원 데이터

In [58]:
# 이차원 데이터

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2[1] = arr2[1] + 2
arr2

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [ 7,  8,  9]])

In [62]:
# ndarray - 1차원 데이터

arr2[:, 0] 

array([1, 8, 7])

In [64]:
# ndarray - 2차원 데이터

arr2[:, [0]]

array([[1],
       [8],
       [7]])

In [65]:
# True행만 선택 - 불리안 인덱싱

arr2[arr2[:,0]>5]

array([[ 8,  9, 10],
       [ 7,  8,  9]])

In [68]:
arr2[(arr2[:, 1] >= 1) & (arr2[:, 1] <= 7)]

array([[1, 2, 3]])

# 시리즈 

In [4]:
data = {'aa':10,'bb':20,'cc':30,'dd':40, 'ee':50}
sr1 = pd.Series(data, name='국어점수')
sr1

aa    10
bb    20
cc    30
dd    40
ee    50
Name: 국어점수, dtype: int64

In [5]:
sr1 + 1

aa    11
bb    21
cc    31
dd    41
ee    51
Name: 국어점수, dtype: int64

In [6]:
sr1 * 2

aa     20
bb     40
cc     60
dd     80
ee    100
Name: 국어점수, dtype: int64

In [11]:
sr1[(sr1 == 20) | (sr1 == 40)]

bb    20
dd    40
Name: 국어점수, dtype: int64

In [12]:
sr1[(sr1 >= 20) & (sr1<=40)]

bb    20
cc    30
dd    40
Name: 국어점수, dtype: int64

In [13]:
sr1[~((sr1 >= 20) & (sr1<=40))]

aa    10
ee    50
Name: 국어점수, dtype: int64

In [14]:
# isin 멤버함수를 써서 True, False를 뽑아낼 수 있음
# sr1[(sr1 == 20) | (sr1 == 40)]

sr1[sr1.isin([20, 40])]

bb    20
dd    40
Name: 국어점수, dtype: int64

In [ ]:
# sr[(sr >= 20) & (sr<=40)]

sr[sr.between(20, 40)]

In [ ]:
# 인덱스를 이용

In [15]:
sr1.index == 'bb'

array([False,  True, False, False, False])

In [16]:
sr1[sr1.index == 'bb']

bb    20
Name: 국어점수, dtype: int64

In [21]:
sr1[sr1.index.isin(['aa', 'cc'])]

aa    10
cc    30
Name: 국어점수, dtype: int64

In [38]:
sr1[sr1.index.isin(['aa'])]

aa    10
Name: 국어점수, dtype: int64

# 데이터프레임

In [43]:
data =  {'eng':[10,30,50,70],
         'kor':[20,40,60,80],
         'math':[90,50,20,70]}
df1 = pd.DataFrame(data,index=['a','b','c','d'])
df1

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

In [24]:
df1 + 1

eng  kor  math
a   11   21    91
b   31   41    51
c   51   61    21
d   71   81    71

In [25]:
df1 * 2

eng  kor  math
a   20   40   180
b   60   80   100
c  100  120    40
d  140  160   140

In [27]:
# 특정 칼럼만 연산하고 싶을 때

df1['eng'] = df1['eng'] + 2
df1

eng  kor  math
a   12   20    90
b   32   40    50
c   52   60    20
d   72   80    70

In [32]:
# 칼럼에 대해서는 위의 방법을 사용하는게 더 직관적인 듯

df1.loc[:,'eng'] = df1.loc[:,'eng'] + 2
df1

eng  kor  math
a   16   20    90
b   36   40    50
c   56   60    20
d   76   80    70

In [33]:
# 특정 행에 대한 연산

df1.loc['a'] = df1.loc['a'] + 2
df1

eng  kor  math
a   18   22    92
b   36   40    50
c   56   60    20
d   76   80    70

In [34]:
# 특정 영역 수정

df1.loc['b':'c', 'kor':] = df1.loc['b':'c', 'kor':] + 2
df1

eng  kor  math
a   18   22    92
b   36   42    52
c   56   62    22
d   76   80    70

### 불리안 인덱싱 - 행 단위

In [35]:
df1[[True, False, False, True]]

eng  kor  math
a   18   22    92
d   76   80    70

In [39]:
# 데이터프레임 전체를 출력

df1[df1['eng'] > 30]

eng  kor  math
b   36   42    52
c   56   62    22
d   76   80    70

In [40]:
# 일부 칼럼 추출

df1[df1['eng'] > 30][['eng', 'kor']]

eng  kor
b   36   42
c   56   62
d   76   80

In [44]:
df1[(df1['kor'] == 20) | (df1['kor'] == 60)]

eng  kor  math
a   10   20    90
c   50   60    20

In [46]:
df1[df1['kor'].isin([20, 40])]

eng  kor  math
a   10   20    90
b   30   40    50

In [45]:
df1[(df1['kor'] >= 20) & (df1['kor'] <= 60)]

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20

### 데이터프레임은 쿼리문을 이용할 수도 있음
### 쿼리문 안에는 문자열이 와야 함

In [49]:
df1.query('eng>30')

eng  kor  math
c   50   60    20
d   70   80    70

In [50]:
df1.query('eng == 10 and kor == 20')

eng  kor  math
a   10   20    90

In [52]:
df1.query('eng == 10 or kor == 80')

eng  kor  math
a   10   20    90
d   70   80    70

In [53]:
df1.query('20 < eng <100')

eng  kor  math
b   30   40    50
c   50   60    20
d   70   80    70

In [55]:
# 방법 1

num = 30
df1[df1['eng'] > num]
df1

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

In [56]:
# 방법 2 - 쿼리문 안에는 문자열이 와야하기 때문에 포메팅 이용

num = 30
df1.query(f'eng > {num}')
df1

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70