In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 넘파이 : 1차원 데이터

In [2]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

In [3]:
arr.sum()

# np.sum(arr) 가능

165

In [4]:
arr.mean()

33.0

In [5]:
arr.max()

55

In [6]:
arr.min()

11

In [7]:
# 가장 큰 값의 인덱스

arr.argmax()

4

In [8]:
# 가장 작은 값의 인덱스

arr.argmin() 

0

In [9]:
arr.std()

15.556349186104045

In [10]:
# np로 하는 것은 ndarray 객체의 멤버함수가 없다는 것

np.median(arr)

33.0

In [11]:
np.quantile(arr, 0.5)

33.0

In [12]:
np.quantile(arr, (0.25, 0.5, 0.75))

array([22., 33., 44.])

In [13]:
# quantile과 단위만 다르지 결과는 같음

np.percentile(arr,[25, 50, 75])

array([22., 33., 44.])

In [14]:
# 국어점수 top5를 구하시요

kor = np.array( [60,55,70,30,20,90])
kor

np.sort(kor)[-1:-6:-1] # -5까지

array([90, 70, 60, 55, 30])

# 넘파이 : 2차원 데이터

<pre>
디폴트 axis=None ==> 1차원의 통계<br>
axis=0           ==> 컬럼별 통계값<br>
axis=1           ==> row별 통계값<br>
</pre>

In [15]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [16]:
data.sum()

52

In [17]:
data.sum(axis=0)

array([24, 11, 17])

In [18]:
data.sum(axis=1)

array([ 6, 14, 19, 13])

In [19]:
data.mean()

4.333333333333333

In [20]:
data.mean(axis=0) # 칼럼별

array([6.  , 2.75, 4.25])

In [21]:
data.mean(axis=1) # 로우별

array([2.        , 4.66666667, 6.33333333, 4.33333333])

In [22]:
data.max()

10

In [23]:
data.max(axis=0) # 칼럼별

array([10,  5,  8])

In [24]:
data.max(axis=1) # 로우별

array([ 3,  7, 10,  6])

In [25]:
data.argmax()

6

In [26]:
data.argmax(axis=0) # 칼럼별로 가장 큰 값의 인덱스

array([2, 1, 2], dtype=int64)

In [27]:
data.argmax(axis=1) # 로우별로 가장 큰 값의 인덱스

# 인공지능 분류에서 많이 활용...

array([2, 0, 0, 0], dtype=int64)

### for문

In [28]:
# 이차원인 경우엔 행 단위로 꺼냄
for n in data:
    print(n)

[1 2 3]
[7 5 2]
[10  1  8]
[6 3 4]


In [29]:
for a, b, c in data:
    print(a, b, c)

1 2 3
7 5 2
10 1 8
6 3 4


# 시리즈

In [30]:
data = {'aa':10,'bb':20,'cc':30,'dd':40,'ee':50}
sr = pd.Series(data, name='국어점수')
sr

aa    10
bb    20
cc    30
dd    40
ee    50
Name: 국어점수, dtype: int64

In [38]:
sr.head(2)

aa    10
bb    20
Name: 국어점수, dtype: int64

In [39]:
sr.tail(2)

dd    40
ee    50
Name: 국어점수, dtype: int64

In [40]:
sr.sum()

150

In [41]:
sr.mean()

30.0

In [42]:
sr.max()

50

In [43]:
sr.min()

10

In [44]:
# 가장 큰 값의 인덱스

sr.idxmax()

'ee'

In [45]:
# 가장 작은 값의 인덱스

sr.idxmin()

'aa'

In [46]:
# 45 이하인 데이터의 가장 큰 값을 구하시요.
sr[sr<=45].max()
# sr1 = sr[sr<=45]
# sr1.max()

40

In [47]:
sr.median()

30.0

In [48]:
sr.std()

15.811388300841896

In [49]:
sr.quantile([0.25, 0.5, 0.75])

0.25    20.0
0.50    30.0
0.75    40.0
Name: 국어점수, dtype: float64

In [31]:
sr.nlargest(2) # top 디폴트 값이 5

ee    50
dd    40
Name: 국어점수, dtype: int64

In [32]:
# keep인자가 first면 동점일 때 가장 먼저오는 값을 꺼내옴

sr.nlargest(2, keep='last')

ee    50
dd    40
Name: 국어점수, dtype: int64

In [33]:
sr.nlargest(2, keep='all')

ee    50
dd    40
Name: 국어점수, dtype: int64

In [34]:
sr.nsmallest(2)

aa    10
bb    20
Name: 국어점수, dtype: int64

In [35]:
sr.unique()

array([10, 20, 30, 40, 50], dtype=int64)

In [36]:
# 각각의 값이 몇개 있는지 

sr.value_counts() 

30    1
20    1
10    1
50    1
40    1
Name: 국어점수, dtype: int64

### 함수

In [50]:
# 함수 만들기 방법1

def fn(v):
    if v>30:
        return v + 1
    else:
        return v + 2

In [51]:
# 함수 만들기 방법2

def fn(v):
    return v+1 if v>30 else v+2

In [52]:
# 리턴값은 시리즈

sr.apply(fn)

aa    12
bb    22
cc    32
dd    41
ee    51
Name: 국어점수, dtype: int64

In [53]:
sr.apply(lambda v : v+1 if v>30 else v+2)

aa    12
bb    22
cc    32
dd    41
ee    51
Name: 국어점수, dtype: int64

In [54]:
# 국어 점수가 40점 이상이면 '합격' 아니면 '불합격'으로 구하시오

sr.apply(lambda v : '합격' if v>=40 else '불합격')

aa    불합격
bb    불합격
cc    불합격
dd     합격
ee     합격
Name: 국어점수, dtype: object

In [55]:
sr

aa    10
bb    20
cc    30
dd    40
ee    50
Name: 국어점수, dtype: int64

In [56]:
# cut : 시리즈 중 가장 작은 값과 가장 큰 값 사이의 구간 개수를 정해서 계급을 나눔
# 그러고나서 어느 계급에 속하는지 표시

pd.cut(sr, 5)

aa    (9.96, 18.0]
bb    (18.0, 26.0]
cc    (26.0, 34.0]
dd    (34.0, 42.0]
ee    (42.0, 50.0]
Name: 국어점수, dtype: category
Categories (5, interval[float64]): [(9.96, 18.0] < (18.0, 26.0] < (26.0, 34.0] < (34.0, 42.0] < (42.0, 50.0]]

In [57]:
# 도수분포랑 같은 개념

pd.cut(sr, 5).value_counts().sort_index()

(9.96, 18.0]    1
(18.0, 26.0]    1
(26.0, 34.0]    1
(34.0, 42.0]    1
(42.0, 50.0]    1
Name: 국어점수, dtype: int64

In [58]:
# 직접 계급을 지정할 수 있음

pd.cut(sr, [0, 20, 40, 60]) 

aa     (0, 20]
bb     (0, 20]
cc    (20, 40]
dd    (20, 40]
ee    (40, 60]
Name: 국어점수, dtype: category
Categories (3, interval[int64]): [(0, 20] < (20, 40] < (40, 60]]

In [59]:
pd.cut(sr, [0, 20, 40, 60]).value_counts().sort_index()

(0, 20]     2
(20, 40]    2
(40, 60]    1
Name: 국어점수, dtype: int64

In [60]:
# 라벨 붙이기

pd.cut(sr, [0, 20, 40, 60], labels=['C', 'B', 'A'])

aa    C
bb    C
cc    B
dd    B
ee    A
Name: 국어점수, dtype: category
Categories (3, object): ['C' < 'B' < 'A']

### for문

In [62]:
# 값 추출

for n in sr: # sr.values => 값만 추출
    print(n)

10
20
30
40
50


In [63]:
# 인덱스 추출

for n in sr.index:
    print(n)

aa
bb
cc
dd
ee


In [64]:
# 인덱스와 값을 튜플로 출력하기 때문에 각각을 unpacking

for n in sr.items():
    print(n)

('aa', 10)
('bb', 20)
('cc', 30)
('dd', 40)
('ee', 50)


In [65]:
for i, v in sr.items():
    print(i, v)

aa 10
bb 20
cc 30
dd 40
ee 50


# 데이터프레임

In [86]:
data =  {'eng':[10,30,50,70],
         'kor':[20,40,60,80],
         'math':[90,50,20,70]}
df = pd.DataFrame(data,index=['a','b','c','d'])
df

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

<pre>
- 디폴트 axis=0 (컬럼별)
- axis=1 (row별)
</pre>

In [87]:
df.sum() # 칼럼별
# df.sum(axis=0) 

# 시리즈로 반환
# 넘파이에서는 전체 합

eng     160
kor     200
math    230
dtype: int64

In [88]:
# 시리즈로 반환
df.sum(axis=1)

a    120
b    120
c    130
d    220
dtype: int64

In [89]:
# 전체 합 구하기
df.sum().sum()

590

In [90]:
# 데이터프레임을 시리즈로 변환 - 멀티 인덱스가 생김
sr = df.unstack()
sr

eng   a    10
      b    30
      c    50
      d    70
kor   a    20
      b    40
      c    60
      d    80
math  a    90
      b    50
      c    20
      d    70
dtype: int64

In [97]:
# 멀티인덱스
sr['eng']['a']

10

In [98]:
# 데이터 전체 합 구하기
df.unstack().sum()

590

In [99]:
df.mean()

eng     40.0
kor     50.0
math    57.5
dtype: float64

In [100]:
df.mean(axis=1).round(2)

a    40.00
b    40.00
c    43.33
d    73.33
dtype: float64

In [101]:
df.mean().mean()

49.166666666666664

In [102]:
df.values.mean()

49.166666666666664

In [103]:
df.max()

eng     70
kor     80
math    90
dtype: int64

In [104]:
df.max(axis=1)

a    90
b    50
c    60
d    80
dtype: int64

In [105]:
df.max().max()

90

In [106]:
df.min()

eng     10
kor     20
math    20
dtype: int64

In [107]:
df.idxmax() # 칼럼별 가장 큰 값의 인덱스

eng     d
kor     d
math    a
dtype: object

In [108]:
df.idxmax(axis=1)

a    math
b    math
c     kor
d     kor
dtype: object

In [109]:
df.median()

eng     40.0
kor     50.0
math    60.0
dtype: float64

In [110]:
df.median(axis=1)

a    20.0
b    40.0
c    50.0
d    70.0
dtype: float64

In [111]:
df.std()

eng     25.819889
kor     25.819889
math    29.860788
dtype: float64

In [112]:
df.quantile([0.25, 0.5, 0.75])

eng   kor  math
0.25  25.0  35.0  42.5
0.50  40.0  50.0  60.0
0.75  55.0  65.0  75.0

In [113]:
df.count() # 각 칼럼별 개수

eng     4
kor     4
math    4
dtype: int64

In [114]:
df.describe()
# df.describe()['eng']

eng        kor       math
count   4.000000   4.000000   4.000000
mean   40.000000  50.000000  57.500000
std    25.819889  25.819889  29.860788
min    10.000000  20.000000  20.000000
25%    25.000000  35.000000  42.500000
50%    40.000000  50.000000  60.000000
75%    55.000000  65.000000  75.000000
max    70.000000  80.000000  90.000000

### 함수

In [76]:
# 방법1

# v가 시리즈

def fn(v):
    print('==========')
    print('v=>',v)
    print('==========')
    return v.sum()

In [77]:
df.apply(fn) # 칼럼별

v=> a    10
b    30
c    50
d    70
Name: eng, dtype: int64
v=> a    20
b    40
c    60
d    80
Name: kor, dtype: int64
v=> a    90
b    50
c    20
d    70
Name: math, dtype: int64


eng     160
kor     200
math    230
dtype: int64

In [78]:
df.apply(fn, axis=1) # 로우별

v=> eng     10
kor     20
math    90
Name: a, dtype: int64
v=> eng     30
kor     40
math    50
Name: b, dtype: int64
v=> eng     50
kor     60
math    20
Name: c, dtype: int64
v=> eng     70
kor     80
math    70
Name: d, dtype: int64


a    120
b    120
c    130
d    220
dtype: int64

In [79]:
# 방법2

df.apply(lambda v:v.sum())

eng     160
kor     200
math    230
dtype: int64

In [ ]:
# 국어, 영어, 수학점수의 평균이 70점이상이면
# '합격' 아니면 '불합격' 으로 결과 컬럼을 추가하세요

In [80]:
df['result'] = df.apply(lambda v: '합격' if v.mean()>=70 else '불합격', axis=1)
df

eng  kor  math result
a   10   20    90    불합격
b   30   40    50    불합격
c   50   60    20    불합격
d   70   80    70     합격

In [81]:
df.nlargest(2, 'eng') # 영어 점수가 가장 높은 상위 2개 # 기준 칼럼명을 꼭 줘야 함

eng  kor  math result
d   70   80    70     합격
c   50   60    20    불합격

### for문

In [68]:
# 칼럼 추출

for n in df: # df.columns
    print(n)

eng
kor
math


In [69]:
# 인덱스 추출

for n in df.index: 
    print(n)

a
b
c
d


In [70]:
# df.items()
# 튜플

for n in df.items(): 
    print(n) 

('eng', a    10
b    30
c    50
d    70
Name: eng, dtype: int64)
('kor', a    20
b    40
c    60
d    80
Name: kor, dtype: int64)
('math', a    90
b    50
c    20
d    70
Name: math, dtype: int64)


In [71]:
# 언패킹
for i, sr in df.items(): 
    print(i, sr['a'], sr['b'], sr['c'], sr['d'])

eng 10 30 50 70
kor 20 40 60 80
math 90 50 20 70


In [74]:
# df.iterrows()

for n in df.iterrows(): 
    print(n) 

('a', eng     10
kor     20
math    90
Name: a, dtype: int64)
('b', eng     30
kor     40
math    50
Name: b, dtype: int64)
('c', eng     50
kor     60
math    20
Name: c, dtype: int64)
('d', eng     70
kor     80
math    70
Name: d, dtype: int64)


In [75]:
for i, sr in df.iterrows(): 
    print(i, sr['eng'], sr['kor'], sr['math']) 

a 10 20 90
b 30 40 50
c 50 60 20
d 70 80 70
