### < XOR >
- 서로 같으면 False
- 하나라도 다르면 True

In [11]:
import numpy as np 
import pandas as pd 
import seaborn as sb 
import matplotlib.pyplot as plt
import mglearn
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
import warnings
warnings.simplefilter('ignore')

In [17]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]]) # 특성데이터 2개 (4X2)
y_data = np.array( [[0],[1],[1],[0]]) # 이진분류

In [18]:
model_logi = LogisticRegression(max_iter=1000, verbose=1) 
model_logi.fit(x_data, y_data)

MLPClassifier()

In [19]:
model_logi.coef_ # 가중치 2개

[array([[ 1.69093364e-02, -2.48899936e-01, -2.14758392e-01,
         -2.66635774e-01,  7.62504118e-02,  7.44602689e-02,
         -1.01476426e-07,  2.52565448e-01, -9.86508711e-03,
          2.12505309e-01, -2.93099306e-02, -4.53907400e-03,
         -6.09565004e-02, -1.88152654e-01, -7.92486307e-02,
         -1.24197335e-01, -2.00344021e-02, -2.24551560e-01,
          3.75740828e-01, -6.69476498e-02, -2.55190639e-02,
          6.30287887e-05,  2.66545895e-01, -2.76365924e-02,
         -8.06933717e-03,  1.78729326e-01, -1.27065782e-01,
          1.89239568e-01, -1.11832491e-01, -9.74402626e-04,
         -3.05280885e-01, -1.00875909e-03,  3.25993441e-01,
         -3.47971669e-02, -2.72028471e-01, -4.03763114e-03,
         -4.58088039e-03,  2.13988415e-01,  3.83923930e-02,
          8.27945090e-02,  5.22438575e-09,  8.91630499e-03,
         -3.26692976e-01,  8.51759459e-09,  3.98504810e-01,
          1.18432753e-01, -7.35708758e-03, -2.35409655e-02,
          7.31348992e-07,  7.63149107e-0

In [14]:
model_logi.score( x_data, y_data )

0.5

In [15]:
model_logi.predict( x_data ) # xor 문제 => 에측을 못함

array([0, 0, 0, 0])

## 로지스틱으로는 안됨

# <NN - 히든레이어 하나>

In [22]:
model_MLP = MLPClassifier() # 디폴트 hidden_layer_sizes=(100,) # 히든레이어 1개
model_MLP.fit(x_data, y_data)

MLPClassifier()

In [23]:
model_MLP.coefs_ # s 붙여주기!!

[array([[ 2.07423557e-05,  2.79403999e-01, -4.73033787e-03,
          2.66737191e-01, -1.57213577e-01, -1.70418689e-01,
         -6.19437372e-02,  2.30514731e-01, -8.75958637e-02,
          2.20720792e-01,  2.69026283e-01,  2.06279135e-01,
          5.69282286e-07,  2.70867669e-01, -8.59198613e-02,
          7.16098891e-05, -5.86276637e-02,  3.86537629e-02,
          1.39734688e-01, -7.31111140e-02,  2.10549215e-01,
          5.27207436e-02, -2.41163852e-01,  2.76118262e-01,
         -8.44039567e-02,  3.13287755e-01,  3.83743120e-02,
         -3.55038284e-02, -2.63084252e-01,  3.43031879e-02,
          4.56733835e-02, -1.26342823e-01,  1.86786377e-01,
          2.37857318e-03, -2.16319066e-01,  1.19032555e-05,
          1.69710624e-01,  1.76793754e-05, -3.99254103e-02,
         -6.39233752e-03,  7.05192281e-02, -2.76067090e-01,
         -6.04607372e-02, -2.38496030e-01, -1.90449425e-01,
         -2.60259397e-01,  1.78688902e-01,  7.63450723e-02,
          5.91921924e-07,  3.20814395e-0

In [24]:
model_MLP.score( x_data, y_data )

1.0

In [25]:
model_MLP.predict( x_data )

# 분류가 됨을 알 수 있다!!

array([0, 1, 1, 0])

In [28]:
model_MLP.intercepts_

[array([-6.94860624e-02,  1.36753974e-04, -1.08234745e-01, -1.58896168e-02,
         2.54831185e-01,  1.70271779e-01, -2.86083777e-02, -1.50276001e-01,
         2.49240564e-01,  2.91498375e-02, -2.68567380e-01, -1.55434927e-01,
        -2.30519043e-01,  2.57920598e-04,  2.30688224e-01, -1.23438543e-01,
         7.12615681e-02,  1.49658673e-01,  3.32228170e-02, -1.37361690e-01,
        -2.10301338e-01, -6.43451508e-02,  2.40379220e-01, -5.02807068e-02,
         1.05555599e-01,  2.37624981e-05,  1.95912704e-01, -1.74882300e-01,
         2.62966848e-01,  2.48143938e-01,  1.51425547e-01,  1.97891805e-01,
        -1.86467945e-01, -1.05067718e-01,  2.16424469e-01, -1.68640267e-01,
        -1.69363208e-01, -1.00829846e-01, -1.80981397e-01,  1.52962033e-01,
         2.56396089e-01, -8.99416610e-03,  7.84479759e-02,  2.38091623e-01,
         1.89565849e-01,  3.05202752e-04, -9.09374288e-05,  2.26451077e-01,
        -1.13453285e-01, -5.30363307e-02, -7.27795470e-05, -1.91105847e-01,
         5.2

In [27]:
len(model_MLP.intercepts_)

2

In [31]:
model_MLP.coefs_[0].shape # 특성데이터 개수 2개

(2, 100)

In [32]:
model_MLP.coefs_[1].shape

(100, 1)

In [ ]:
## 4x2 2x100 100x1
##  4x100
##       4x1

In [34]:
# 4x100 => 100개의 절편
# 내보내는 값을 따름

model_logi.intercepts_[0].shape

(100,)

In [35]:
model_logi.intercepts_[1].shape

(1,)

# <NN - 히든레이어 두 개>

In [50]:
model_MLP = MLPClassifier(hidden_layer_sizes=(200, 4)) # 히든레이어 2개
model_MLP.fit(x_data, y_data)

MLPClassifier(hidden_layer_sizes=(200, 4))

In [69]:
len(model_MLP.intercepts_)

3

In [70]:
model_MLP.intercepts_[0].shape 

(200,)

In [71]:
model_MLP.intercepts_[1].shape 

(4,)

In [72]:
model_MLP.intercepts_[2].shape 

(1,)

In [58]:
len(model_MLP.coefs_)

3

In [62]:
model_MLP.coefs_[0].shape # 200개의 노드를 가진 히든레이어 첫번쨰

(2, 200)

In [63]:
model_MLP.coefs_[1].shape # 4개의 노드를 가진 히든레이어 

(200, 4)

In [64]:
model_MLP.coefs_[2].shape

(4, 1)

In [55]:
model_MLP.predict( x_data )

array([0, 1, 1, 0])

In [66]:
model_MLP.predict( [[0, 1], [0, 0]] )

array([1, 0])

### 중간 레이어 계층은 relu를 통과하고 마지막에는 시그모이드 활성함수를 통해서 아웃풋

### 활성함수 layer 층은 relu 함수를 통과
### output은 sigmoid 함수를 통과(이진 분류는 무조건 시그모이드 / 다중 분류는 soft max)

### => 히든레이어를 늘리고 싶으면 hidden_layer_sizes=(200, 10, 4) 이렇게 늘리기

In [73]:
model_MLP = MLPClassifier(hidden_layer_sizes=(100, 50, 30, 20)) 
model_MLP.fit(x_data, y_data)

MLPClassifier(hidden_layer_sizes=(100, 50, 30, 20))

In [74]:
model_MLP.predict( x_data )

array([0, 1, 1, 0])

In [80]:
len(model_MLP.coefs_)

5

In [81]:
model_MLP.coefs_[0].shape

(2, 100)

In [82]:
model_MLP.coefs_[1].shape

(100, 50)

In [83]:
model_MLP.coefs_[2].shape

(50, 30)

In [84]:
model_MLP.coefs_[3].shape

(30, 20)

In [85]:
model_MLP.coefs_[4].shape

(20, 1)

# <파라미터 설명>

## 하이퍼파라미터 튜닝을 통해서 과적합을 막자!
### activation='relu'
###### - Gradient vanishing(기울기 소실) 문제해결
### solver :  'adam'  
###### -학습을 할 때 보폭을 조절
###### - 'lbfgs', 'sgd', 'adam'
### alpha=0.0001
### max_iter=200
### learning_rate='constant'