판다스 : 데이터의 가공, 변환, 정제, 수집, 전처리, 통계, 시각화
-	데이터 수집 : 텍스트, CSV, Excel, Html:Beautifulsoup, Xml, Hdfs, 데이터베이스, json
-	데이터 전처리 : 분석 가능한 형태로 변형, Null 처리, 이상치
-	데이터 분석 : 통계, 시각화(matplotlib, seaborn)
-	예측 : sklearn, Tensorflow, keras, pytorch, statesmodels, scypython -> 판다스에서는 예측 및 분류쪽은 지원하지 않음 / sklearn은 머신러닝 라이브러리, 딥러닝 약간 지원 / 딥러닝쪽은 Tensorflow, keras, pytorch

In [1]:
import numpy as np
# 리스트의 확장판(데이터연산, 통계분석), numpy 확장판 pandas

- edit mode(연두색) : tab(자동완성), shift + tab(아규먼트), ctrl + enter(코드실행), shift + enter(코드실행후 아래로 셀 이동)
                    , esc(커맨드 모드 전환), ctrl + /(주석 및 제거)

- command mode(하늘색) : enter(edit mode), a(위에 셀 추가),b(아래에 셀 추가), x(셀 삭제), z(삭제 취소), o(결과 접었다 펼쳤다)
    , m(해당셀 주석셀), y(코드셀)
    
print 없이 출력은 jupyter 자체 스타일이 적용

# 여기는 주석셀
## 테스트 1
### 테스트 2

<h1>테스트</h1>
<h2>테스트</h2>
<img src="image/a.png">
여기는<br>
테스트

In [2]:
print('hello')

hello


In [4]:
a = 10
b = 20
# print(a)
# print 없이 출력은 jupyter 자체 스타일이 적용
a
b

20

## <용어 정리>

### - scalar : 상수값(10, 3.14, 'korea')

### 스칼라를 모아놓은 것이 벡터
### - vector(1차원) : [10, 20, 30]
### - matrix(2차원) : [[10, 20, 30], [100, 200, 300]] 2x3
### - 3차원 : [[[10, 20, 30], [100, 200, 300]], [[10, 20, 30], [100, 200, 300]]] 2x2x3

파이썬은 모든 것이 객체<br>
객체 : 속성 + 메소드<br>
    객체.속성<br>
    객체.메소드() # 탭 눌러서 자동완성 보기

In [6]:
my = [10, 20, 30]
print(type(my))
# 리스트와 다르게 넘파이 배열은 더 많은 메소드를 가진다

<class 'list'>


# 1. ndarray 배열 방법

In [5]:
arr1 = np.array([10, 20, 3])
print(type(arr1))
print(arr1) # 배열은 콤마가 없이 나옴
arr1 # 프린트 없이 객체를 찍으면 주피터 자체 스타일이 적용 -> 콤마 있음

<class 'numpy.ndarray'>
[10 20  3]


array([10, 20,  3])

In [8]:
arr2 = np.array( [[10, 20, 30], [100, 200, 300]])
print(arr2)
arr2

[[ 10  20  30]
 [100 200 300]]


array([[ 10,  20,  30],
       [100, 200, 300]])

# 2. ndarray 배열 방법

In [9]:
arr3 = np.arange(1, 11, 1) # 1 <= arr < 11 1씩 증가)
arr3 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr4 = np.arange(1, 11, 2) # 1 <= arr < 11 2씩 증가)
arr4

array([1, 3, 5, 7, 9])

# 3. ndarray 배열 방법(랜덤)

In [11]:
arr5 = np.random.randint(1, 11, size=5)
arr5

array([9, 2, 8, 6, 8])

In [12]:
arr6 = np.random.randint(1, 11, size=(3, 2))
arr6

array([[ 3,  5],
       [ 3,  2],
       [10,  2]])

In [17]:
np.random.rand(5) # 0~1 사이 임의의 실수값 반환

array([0.31102834, 0.77210478, 0.52791035, 0.13164336, 0.13592051])

In [20]:
np.random.rand(2, 3) # 0~1 사이 임의의 실수값 반환

array([[0.75380498, 0.40172312, 0.1191544 ],
       [0.95897283, 0.32922367, 0.2159506 ]])

In [21]:
np.random.randn(5) # 표준정규분포(평균이 0 편차1)를 따르는 임의의 값을 반환

array([ 1.9918092 ,  0.16155884, -0.56981051, -1.02642293,  0.17579645])

In [22]:
np.random.randn(2, 3)

array([[-0.20540178,  1.12205365, -0.4675246 ],
       [-1.77359931,  0.81669664,  1.58923742]])

In [23]:
np.random.choice([1, 2, 3, 4, 5], 3) # 1, 2, 3, 4, 5 중에 임의로 3개 뽑기

array([3, 2, 2])

In [31]:
np.random.choice(np.arange(1, 11), 5, replace=False) # replace=False 비복원 추출

array([10,  5,  8,  3,  9])

In [32]:
arr6 = np.arange(1, 11)
np.random.shuffle(arr6)
arr6 # 데이터가 임의로 재배치됨

array([ 9,  1,  2, 10,  7,  8,  5,  3,  4,  6])

# 4. ndarray 배열 방법

In [35]:
arr7 = np.int32([1, 2, 3, 4, 5]) # 하나가 메모리 4byte
# np.array([1, 2, 3, 4, 5], dtype=np.int32) # 타입을 직접 지정할 수 있음
arr7

array([1, 2, 3, 4, 5])

In [36]:
np.int64([1, 2, 3, 4, 5]) # 하나가 메모리 8byte

array([1, 2, 3, 4, 5], dtype=int64)

In [39]:
np.float32([1, 2, 3, 4, 5])

array([1., 2., 3., 4., 5.], dtype=float32)

In [40]:
np.array([1, 2, 3, 4, 5], dtype=np.str) # 요소 하나가 문자열로 

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [41]:
np.ones(3) # 1로만 구성

array([1., 1., 1.])

In [42]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.zeros(3) # 0으로만 구성

array([0., 0., 0.])

In [44]:
np.eye(3) # sparse 매트릭스(희소행렬 혹은 대각행렬) one hot encoding -> 분류에서 많이 사용

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.linspace(1, 10) # 간격이 균일하게 50개를 만들어줌

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [51]:
v, c = np.unique([1, 2, 2, 3, 3, 3, 4, 4, 5], return_counts=True) # 중복제거
print(v)
print(c)

[1 2 3 4 5]
[1 2 3 2 1]


In [52]:
for a, b in zip(v, c):
    print(a,b)

1 1
2 2
3 3
4 2
5 1
