In [1]:
import numpy as np

In [2]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

# 핵심 속성

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.size

5

In [6]:
arr.shape # 벡터는 칼럼이 없어서 튜플로 나옴

(5,)

In [7]:
arr.ndim

1

In [8]:
arr1 = np.array([[11, 22], [33, 44], [55, 66]])
arr1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [9]:
arr1.shape

(3, 2)

In [10]:
arr1.size

6

In [11]:
arr1.T # 행과 열 뒤바뀜

array([[11, 33, 55],
       [22, 44, 66]])

# 형 변환

In [15]:
arr.dtype

dtype('int32')

In [16]:
arr = arr.astype(np.int64) # type 바꾸기

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr.astype(np.float64)

array([11., 22., 33., 44., 55.])

In [19]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2

array([1, 2, 3, 4, 5, 6])

In [20]:
arr2.reshape(3, 2) # shape 바꾸기

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
arr2.reshape(-1, 3) # -1 : 알아서 결정

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2

array([1, 2, 3, 4, 5, 6])