In [1]:
import numpy as np

In [2]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

# 인덱싱

In [3]:
arr[0]

11

In [4]:
arr[-1]

55

In [5]:
arr[[0, 2, 3]] # 복수개의 인덱스 선택

array([11, 33, 44])

## boolean indexing

In [6]:
arr[[True, True, False, False, True]]

array([11, 22, 55])

## slicing(슬라이싱)

In [8]:
# [시작:끝:증가치]
arr[1:4:1] # 1 <= idx < 4 1, 2, 3

array([22, 33, 44])

In [10]:
arr[1:4:2]

array([22, 44])

In [11]:
arr[:4]

array([11, 22, 33, 44])

In [12]:
arr[:-1] # 0 <= idx < -1

array([11, 22, 33, 44])

In [60]:
arr[-1:-4:-1] # -1 <= idx < -4 -1, -2, -3

array([55, 44, 33])

In [13]:
arr[:-4:-1]

array([55, 44, 33])

In [61]:
arr

array([11, 22, 33, 44, 55])

# 연산(산술, 관계, 논리)
#### element wise(요소별 연산)

In [14]:
arr+2

array([13, 24, 35, 46, 57])

In [15]:
arr*2

array([ 22,  44,  66,  88, 110])

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [17]:
arr + arr1

array([12, 24, 36, 48, 60])

In [9]:
arr

array([11, 22, 33, 44, 55])

In [18]:
arr1

array([1, 2, 3, 4, 5])

In [19]:
#연봉데이터가 있을때 각연봉에 대한
# 세금 3.3을 제한 실수령액을 구하시요
salary = np.array( [1000,2000,3000,4000,5000])

In [20]:
salary*(1-0.033)

array([ 967., 1934., 2901., 3868., 4835.])

# 관계연산자

In [22]:
arr > 30
# 요소별로 확인 -> element wise

array([False, False,  True,  True,  True])

In [23]:
# arr[[True, True, False, False, True]]
# 불리언 인덱싱 -> True에 해당하는 것만 나옴
arr[arr > 30]

array([33, 44, 55])

In [25]:
# 불리언 인덱싱
arr[arr == 44]

array([44])

In [ ]:
# 논리 연산자
# and ==> &, or ==> |, not ==> ~

In [28]:
(arr == 11) | (arr == 55)

array([ True, False, False, False,  True])

In [29]:
# 불리언 인덱싱
arr[(arr == 11) | (arr == 55)]

array([11, 55])

In [30]:
(arr>20) & (arr<50)

array([False,  True,  True,  True, False])

In [31]:
# 불리언 인덱싱
arr[(arr>20) & (arr<50)]

array([22, 33, 44])

In [32]:
~((arr == 11) | (arr == 55))

array([False,  True,  True,  True, False])

In [33]:
# 불리언 인덱싱
arr[~((arr == 11) | (arr == 55))]

array([22, 33, 44])

In [21]:
arr

array([11, 22, 33, 44, 55])

In [47]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])
name

array(['홍길동', '김철수', '임꺽정', '김철이', '이황'], dtype='<U3')

In [48]:
# '철' 글자가 있는 데이터를 보여주시오

In [59]:
[n for n in name if '철' in n]

['김철수', '김철이']

In [58]:
'철' in name[3]

True

In [51]:
# 힌트
s = 'hello korea'
'llo' in s

True