In [1]:
import numpy as np

In [2]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

# 추가

In [5]:
arr = np.append(arr, [100, 200])

In [6]:
arr

array([ 11,  22,  33,  44,  55, 100, 200])

In [7]:
np.insert(arr, 1, [1, 2])

array([ 11,   1,   2,  22,  33,  44,  55, 100, 200])

# 수정

In [12]:
arr[0] = 111

In [14]:
arr[1:3] = [222, 333]

In [16]:
arr[3:5] = arr[3:5] + 2

In [ ]:
# 200보다 큰 데이터에 대해 기존값에 2를 더한 것으로 수정하시오

In [21]:
arr[arr>200] = arr[arr>200] + 2

In [22]:
arr

array([111, 224, 335,  46,  57, 100, 200])

# 삭제

In [23]:
np.delete(arr, [0, 2])

array([224,  46,  57, 100, 200])

In [27]:
np.where(arr<100) # where 함수는 조건에 대한 인덱스를 반환

(array([3, 4], dtype=int64),)

In [30]:
# 100 이상인 값을 삭제하시오

np.delete(arr, np.where(arr>=100))

array([46, 57])

# 조건별 데이터 연산

In [34]:
np.where(arr>=100, 'A', 'B') 

array(['A', 'A', 'A', 'B', 'B', 'A', 'A'], dtype='<U1')

In [35]:
conList = [arr>200, arr>100, arr>0]
choiceList = ['A', 'B', 'C']
np.select(conList,choiceList) # 다중조건은 select함수 이용

array(['B', 'A', 'A', 'C', 'C', 'C', 'B'], dtype='<U11')

In [36]:
arr

array([111, 224, 335,  46,  57, 100, 200])

# 정렬

In [37]:
# 오름차순
np.sort(arr)

array([ 46,  57, 100, 111, 200, 224, 335])

In [39]:
# 내림차순
np.sort(arr)[-1::-1]

array([335, 224, 200, 111, 100,  57,  46])

In [40]:
# 오름차순에 대한 인덱스
# np에서 arg붙은 것은 인덱스
np.argsort(arr)

array([3, 4, 5, 0, 6, 1, 2], dtype=int64)

In [41]:
arr[np.argsort(arr)]

array([ 46,  57, 100, 111, 200, 224, 335])

In [47]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])
[n for n in name if ('철' in n)] 
# 리스트내포를 사용해서 할 수도 있음 [표현식 for 항목 in 반복가능객체 if 조건문]

['김철수', '김철이']

In [44]:
np.char.find(name, '철') 
# '철'이라는 글자가 없으면 -1 / 있으면 있는 곳의 인덱스를 알려줌
# 찾은 문자열의 인덱스를 출력

array([-1,  1, -1,  1, -1])

In [46]:
name[np.char.find(name, '철') >= 0]

array(['김철수', '김철이'], dtype='<U3')

In [38]:
arr

array([111, 224, 335,  46,  57, 100, 200])

# char 도큐먼트
https://numpy.org/doc/stable/reference/routines.char.html