In [1]:
import numpy as np

In [2]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

<통계><br>
ndarray 객체의 멤버함수 + np의 함수<br>
np의 함수

In [3]:
arr.sum()

165

In [4]:
np.sum(arr)

165

In [5]:
arr.mean()

33.0

In [6]:
np.mean(arr)

33.0

In [7]:
arr.max() # np.max(arr)

55

In [8]:
arr.min()

11

In [9]:
arr.argmax() # 가장 큰 값의 인덱스 - arg는 인덱스를 말함
# np.argmax(arr)

4

In [10]:
arr.argmin() # 가장 작은 값의 인덱스

0

In [11]:
arr.std()

15.556349186104045

In [12]:
# np로 하는 것은 ndarray 객체의 멤버함수가 없다는 것
np.median(arr) # 데이터를 정렬했을 때 가운데값

33.0

In [15]:
arr1 = np.array([11, 22, 33, 44, 55, 66])
arr1

array([11, 22, 33, 44, 55, 66])

In [16]:
np.median(arr1)

38.5

In [17]:
np.quantile(arr, 0.5) # 사분위수 - 데이터를 정렬했을 때 50%에 해당하는 값

33.0

In [18]:
np.quantile(arr, (0.25, 0.5, 0.75))

array([22., 33., 44.])

In [19]:
np.percentile(arr,[25, 50, 75]) # quantile과 단위만 다르지 결과는 같음

array([22., 33., 44.])

# 연습문제

In [39]:
kor = np.array( [60,55,70,30,20,90])
kor

array([60, 55, 70, 30, 20, 90])

In [40]:
# 1. 국어점수가 가장 큰 값을 구하시요
kor.max()

90

In [41]:
# 2. 국어점수가 80점 이상인 값을 구하시요
kor[kor>=80]

array([90])

In [42]:
# 3. 국어점수가 50점이상 80이하인 값을 구하시요

kor[(kor>=50) & (kor<=80)]

array([60, 55, 70])

In [43]:
# 4. 국어점수의 평균을 구하시요.

kor.mean()

54.166666666666664

In [44]:
# 5. 국어점수의 총합을 구하시요.

kor.sum()

325

In [45]:
# 6. 국어점수가 40점이하인 데이터를 삭제하시요

np.delete(kor, np.where(kor<=40))

array([60, 55, 70, 90])

In [46]:
# 7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하시요.

kor[kor>=50] = kor[kor>=50] * 1.1
kor

array([66, 60, 77, 30, 20, 99])

In [47]:
# 8. 국어점수 top5를 구하시요

np.sort(kor)[-1:-6:-1] # -5까지

array([99, 77, 66, 60, 30])

In [49]:
np.where(kor >= 70, '합격', '불합격')

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')

In [48]:
# 9. 국어점수가 70점 이상이면 '합격', 아니면 '불합격' 으로
# 아래와 같이 출력하시요

# 60 '불합격'
# 55 '불합격'
# ...

for s, r in zip(kor,np.where(kor >= 70, '합격', '불합격')):
    print(s,r)

66 불합격
60 불합격
77 합격
30 불합격
20 불합격
99 합격
